# Dagster instance deployment to kubernetes, using helm chart overwrite via kustomization

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dagster

resources:
  - namespace.yaml
  - ingressroute.yaml
  - sealed-secrets/dagster-secrets-sealed.yaml

helmCharts:
  - name: dagster
    repo: https://dagster-io.github.io/helm
    version: 1.12.8
    releaseName: dagster
    namespace: dagster
    valuesInline:
      global:
        postgresqlSecretName: "postgres-secrets"

      generatePostgresqlPasswordSecret: false

      dagster-user-deployments:
        enable: false
        deployments: []

      dagsterWebserver:
        env:
          - name: DAGSTER_PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secrets
                key: postgresql-password
        workspace:
          enabled: true
          servers:
            - host: "crypto-data"
              port: 3030
              name: "crypto-data"
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi

      dagsterDaemon:
        env:
          - name: DAGSTER_PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secrets
                key: postgresql-password
        envSecrets:
          - name: postgres-secrets
        runCoordinator:
          config:
            queuedRunCoordinator:
              maxConcurrentRuns: 6

      runLauncher:
        type: K8sRunLauncher
        config:
          k8sRunLauncher:
            resources:
              limits:
                cpu: 200m
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 128Mi
            runK8sConfig:
              jobSpecConfig:
                ttlSecondsAfterFinished: 600
              containerConfig:
                resources:
                  limits:
                    cpu: 100m
                    memory: 128Mi
                  requests:
                    cpu: 250m
                    memory: 512Mi
            envVars:
              - DAGSTER_PG_PASSWORD

      postgresql:
        enabled: false
        postgresqlHost: postgresql.database.svc.cluster.local
        postgresqlDatabase: dagster
        postgresqlUsername: dagster

      retention:
        enabled: true
